## k8s 扩展资源
# 通过 kubectl proxy 访问apiserver 给节点分配扩展资源
# 1. kubectl proxy
# 2. curl --header "Content-Type: application/json-patch+json" --request PATCH --data '[{"op": "add", "path": "/status/capacity/meloonc.com~1ext", "value":"1"}]' http://localhost:8001/api/v1/<your-node-name>/dell/status
apiVersion: v1
kind: Pod
metadata:
  name: pod-ext-resource
spec:
  containers:
    - name: pod-ext-resource
      image: nginx
      ports:
        - containerPort: 80
      resources:
        ## 扩展资源
        requests:
          meloonc.com/ext: "1"
        limits:
          meloonc.com/ext: "1"
