apiVersion: v1
kind: Pod
metadata: 
  name: pod-hook
  labels:
    app: pod-hook
spec:
  containers:
    - name: pod-hook
      image: nginx
      ports:
        - containerPort: 80
      lifecycle:
        # 容器被创建是被异步调用，不保证在容器入口 entrypoint 启动前先执行
        postStart:
          # 执行命令
          exec:
            command: [
              "/bin/sh",
              "-c",
              "echo hello from postStart handler > /usr/share/message",
            ]
        # 容器终止 terminated 前被同步调用，实现优雅关闭, 如果是 completed 状态不会触发
        preStop:
          exec:
            command: ["/usr/sbin/nginx", "-s", "quit"] # 优雅退出
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 200m
          memory: 200Mi

