apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-pvc
spec:
  selector:
    matchLabels:
      type: local
  # 与 pv 保持一致
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  accessModes:
    # 与 pv 保持一致
    - ReadWriteOnce
