# 全局对象，所有 ns 都可以使用
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    # 允许单个节点上的 pod 读写
    - ReadWriteOnce
    # 允许多个节点上的 pod 只读
    # - ReadOnlyMany
    # 允许多个节点上的 pod 读写
    # - ReadWriteMany
    # 只允许集群中的一个 pod 读写
    # - ReadWriteOncePod
  # 与节点绑定，如果 pod 调度到其他节点，pv 会失效
  hostPath:
    # 宿主机路径
    path: "/data/k8s/test/pv"
