apiVersion: v1
kind: Pod
metadata:
  name: nginx-hostpath-pvc
  labels:
    name: nginx-hostpath-pvc
spec:
  # 需要配置 nodeSelector 才能调度到指定的节点上，指定节点才有 hostpath 类型的 pvc
  nodeSelector:
    kubernetes.io/hostname: dell
  # 声明使用的 pvc
  volumes:
    - name: nginx-hostpath-pvc
      persistentVolumeClaim:
        claimName: hostpath-pvc
  containers:
    - name: nginx-hostpath-pvc
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      # 将 pvc 挂载到容器内的指定目录
      volumeMounts:
        - name: nginx-hostpath-pvc
          mountPath: "/usr/share/nginx/html"
  
