apiVersion: v1
kind: Pod
metadata:
  name: nginx-local-pvc
  labels:
    name: nginx-local-pvc
spec:
  # 声明使用的 pvc
  volumes:
    - name: nginx-local-pvc
      persistentVolumeClaim:
        claimName: local-pvc
  containers:
    - name: nginx-local-pvc
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      # 将 pvc 挂载到容器内的指定目录
      volumeMounts:
        - name: nginx-local-pvc
          mountPath: "/usr/share/nginx/html"
  
