apiVersion: batch/v1
kind: Job
metadata:
  name: job-demo
spec:
  template:
    spec:
      containers:
        - name: job-demo
          image: busybox
          command: ["sh", "-c", "echo hello world"]
      # pod 不重启，会新建
      restartPolicy: Never
  # 失败重试次数，默认 6 次
  backoffLimit: 4
  # job 最大执行时间
  activeDeadlineSeconds: 5
  # 并行执行数量
  parallelism: 2
  # job 执行成功数量
  completeions: 8
## indexed 模式，job 中可以通过环境变量 JOB_COMPLETION_INDEX 获取 job 的执行顺序，用于处理顺序 job
  # completionMode: Indexed


