# secret 挂在 volume 可以热更新
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  key1: dGVzdA==
  key2: dGVzdA==
# stringData 会自动 base64 编码，创建完成自动转换为 data
stringData:
  key3: '123'
  key4: '123'