apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
  # 用来查找 pod
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  replicas: 3
  # 指定 service 名称
  serviceName: nginx
  # 按顺序进行创建或者删除，创建时顺序，删除是逆序
  podManagementPolicy: OrderedReady
  selector:
    # 用来查找 pod
    matchLabels:
      app: nginx
  updateStrategy: 
    type: OnDelete # 当有 apply 时只有手动删除 pod 才能创建新版本的 pod
    # type: RollingUpdate
    # rollingUpdate: 
    #   maxUnavailable: 1  #最多不可用 pod 数量
    #   partition: 3  # 分段更新，如果序号小于 patition 将不会更新，适合灰度部署
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            # 将一下目录挂在到 pv 里面
            - name: www
              mountPath: /usr/share/nginx/html
  # pvc 模板，用来创建一个 pvc, 每个 pvc 会申请一个 pv
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi


