apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-basic-auth-ingress
  annotations:
    # 外部认证路径 user:passwd
    nginx.ingress.kubernetes.io/auth-url: https://httpbin.org/basic-auth/user/passwd
spec:
  ingressClassName: nginx
  rules:
  - host: external.basic.auth.192.168.50.100.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-demo
            port:
              number: 80