apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
spec:
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx-demo
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
spec:
  selector:
    app: nginx-demo
  ports:
  - port: 80
    targetPort: 80
---
# 通过 htpasswd 创建 auth 文件
# 使用 kubectl create secret generic basic-auth  --from-file=./auth 创建 secret
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  auth: bWVsb246JGFwcjEkVWtzc3huRjMkUHc1TlhYdUV1dHNEQXpKcTJ3Q25ZLwo=

